### PR TITLE
Get file diagnostics instead of global diagnostics

### PR DESCRIPTION
**Pull request by bensengupta**
Hey Jarosław, thanks for making this plugin.

I noticed that this plugin was taking up a lot of time and memory in our codebase. I tinkered around with the plugin and discovered that `getSemanticDiagnostics` accepts a `SourceFile`. Passing this file into `getSemanticDiagnostics` yields the same errors but with significantly improved performance. I measured a 5x speed improvement when linting our entire codebase, and linting a single file finishes in milliseconds rather than 20 seconds.

I haven't measured memory usage, but I assume this has been reduced as well.

Should help with: https://github.com/JaroslawPokropinski/eslint-plugin-strict-null-checks/issues/30

### Before

Entire codebase
image

Single file
image

### After

Entire codebase
image

Single file
image

### CODE REVIEW

**Comment by bensengupta** [comment]
Tests are passing
image

**Comment by JaroslawPokropinski** [comment]
Thank you for your contribution. Could you please run the `npm version patch` command?

**Comment by bensengupta** [comment]
> Thank you for your contribution. Could you please run the `npm version patch` command?

Done 👍

**Comment by JaroslawPokropinski** [comment]
closes #30

**Pull request merged**
